# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cancelled',
            field=models.BooleanField(default=False, verbose_name='cancelled'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')], default=0, verbose_name='weekday'),
        ),
    ]
